### PR TITLE
allow stages to pass parameters down to their steps

### PR DESCRIPTION
**Pull request by linead**
# PR Details

## Description

Stages will now pass any arguments to the stages defined within, for example a deployment stage that can contain multiple steps can be re-used with an application environment so that steps can be dynamic based on the environment passed in

See: https://github.com/linead/jte-testing/tree/master/stages-with-envs for a simple example of a stage with behaviour based on stages

## How Has This Been Tested

- Initial testing via unit tests
- Manual testing via a dockerised jenkins instance running jenkins 2.164.3 with the following repos
  - https://github.com/linead/jte-testing/tree/master/stages-with-envs
  - https://github.com/linead/jte-jobs

## Types of Changes

- [x] Added Unit Testing
- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

Not sure about labels to add to the PR, but can update the documentation to reflect this if the code changes look fine

- [ ] I have added the appropriate label for this PR
- [ ] If necessary, I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by linead** [comment]
re-opened @steven-terrana as discussed in #19 - cheers.

**Comment by linead** [comment]
@steven-terrana initially I thought this made the DSL too complicated, there was a certain amount of simplicity in the arguments copying. I have implemented your suggestion in the above commit, it really only adds four letters to the jenkinsfile and avoids requiring all steps to have the same arguments which I agree is a nice solution.

**Comment by linead** [comment]
While running with our existing pipelines we noticed some issues with jenkins trying to serialise the metaclass - moved the code that alters the class into a nonCPS method to avoid these issues.

**Comment by steven-terrana** [comment]
good catch on the not serializable exceptions! This looks good to me, tests are passing, going to merge it in.  Also - you're the first contributor outside of Booz Allen Hamilton and that means a lot to us! thanks for using JTE.    

if you haven't, i'd recommend joining the [JTE Gitter Channel](https://gitter.im/jenkinsci/templating-engine-plugin?source=all-rooms-list).

**Pull request merged**
