### PR TITLE
Upgrade Jenkins Baseline and Gradle

### PR DESCRIPTION
**Pull request by sghill**
# PR Details

Hi :wave:, I maintain the jpi plugin and was looking into how hard upgrades are.

This PR upgrades Jenkins and tools to their last versions that supported Java 8. It also upgrades Gradle to the latest release, updating deprecations with their recommended replacements along the way.

## Description

The [current recommendation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions) for a Jenkins Baseline is 2.375.x and up. Starting with 2.263.1, Jenkins [requires Java 11](https://www.jenkins.io/blog/2022/06/28/require-java-11/) to build. To minimize changes in this PR, I upgraded to the most recent LTS that supports Java 8.

Spotless has been upgraded to [6.13.0](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md#6130---2023-01-14), the last version that does not require Java 11.

The JPI plugin has been upgraded to the latest published version. I can release the final version of 0.50.0 before we merge this if that's preferred. Various properties have been updated to their Gradle [lazy property](https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties) replacements.

The Jenkins-managed plugins bom has been included to determine compatible plugin dependency versions. Plugin dependency versions have been removed if they're in the bom I thought leaving the versions defined was misleading, since conflict resolution with the bom means the bom's version wins anyway.

Additional Groovy source files have been allowed as upgrading Jenkins meant that the `ResumabilitySpec` `Restart mid-step resumes successfully` failed by being disallowed from loading `StepWrapperCPS`. If this is only useful for tests, the extension could be defined in test sources instead.

## How Has This Been Tested

Ran existing tests (`./gradlew clean build`) on an Ubuntu bionic machine

## Types of Changes

- [ ] Added Unit Testing
- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have added the appropriate label for this PR
- [ ] If necessary, I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sghill** [comment]
@steven-terrana is something you'd be interested in?

**Comment by steven-terrana-bah** [comment]
hey @sghill - absolutely! 

Thanks for your patience :) - work has been a bit hectic. 

I'll review this ASAP and get it merged. 

Appreciate you!

**Comment by sghill** [comment]
Awesome! No rush. This test stopped failing for me locally after I added the next extension, not sure why it's failing here 🤔

**Comment by steven-terrana-bah** [comment]
it's been a nagging issue for a while that i can't seem to pin down - it's always worked locally for me too.

**Review by steven-terrana-bah — APPROVED** [review]

**Review by steven-terrana — APPROVED** [review]

**Pull request merged**
